print "Hello World!"
print "Hello Again!"
print "La concha de tu madre Allboys!"
print "YEAH!"
print "One small step for a man..."
print "A huge step for Humanity"
print "The Ace of Spades! The Ace of Spades!"
